[feat] 대시보드 데이터 호출 기능 구현
clapsheep/walk-or-run-server pull request #75
Opened 2024-11-20 06:32 UTC by yujeong789

1. CSV 파일 업로드 이후 파싱해서 DB 삽입
2. 심박수, 걸음수, 칼로리, 케이던스, 누적거리, 평균속도로 나누어 필요한 개별 데이터를 호출할 수 있도록 구현함
3. 모든 데이터 호출 가능한 기능 구현함

참고) 테스트할 때, RecordMapper.xml에서 가장 이상적인 데이터를 호출하기 위해 날짜를 현재 날짜가 아닌 임의의 날짜를 지정해 둠
```
DATE(start_time) = DATE('2024-10-22')
```
위의 코드를 아래의 코드로 변경하면 해당 코드를 작동하는 날짜포함하여 이전 7일간의 데이터를 출력해줌
```
DATE(start_time) = DATE(NOW())
```

2024-11-20 06:44 UTC, rpeowiqu requested changes
db에서 가져온 값이 없을 때 에러가 난 건 아니니까
if문으로 구분해서 값이 없을 땐
new ResponseEntity<>(new ApiResponse("empty", "methodName", 204), HttpStatus.NO_CONTENT);를 반환해주세요

2024-11-20 06:51 UTC, zyu22 submitted a review, later dismissed
수정부탁드립니다

2024-11-20 06:51 UTC, zyu22 commented on src/main/java/com/wor/dash/record/model/service/RecordService.java
> +    List<Calorie> getCalorieData(int userId);
getCalorieList 로 부탁드려요!

2024-11-20 06:51 UTC, zyu22 commented on src/main/java/com/wor/dash/record/model/service/RecordService.java
> +    List<HeartRate> getHeartRateData(int userId);
getHeartRateList로 부탁드려요!

2024-11-20 06:51 UTC, zyu22 commented on src/main/java/com/wor/dash/record/model/service/RecordService.java
> +    List<Record> getRecordData(int userId);
getRecordList로 부탁드려요!

2024-11-20 06:51 UTC, zyu22 commented on src/main/java/com/wor/dash/record/model/service/RecordService.java
> +    List<Step> getStepData(int userId);
getStepList로 부탁드려요!

2024-11-21 00:02 UTC, rpeowiqu submitted a review, later dismissed
승인합니다!

2024-11-21 00:05 UTC, rpeowiqu approved these changes

2024-11-21 00:05 UTC, clapsheep approved these changes

2024-11-21 00:06 UTC, clapsheep approved these changes

2024-11-21 00:07 UTC, merged

2024-11-21 00:08 UTC, zyu22 approved these changes
승인입니다!